---
title: "EDA"
author: "Conor Tompkins"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

theme_set(theme_bw())
```

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(tidytext)
library(ggrepel)
library(hrbrthemes)

theme_set(theme_bw())

options(scipen = 999, digits = 2)
```

```{r}
df <- read_csv("output/migration_data_cleaned.csv") %>% 
  filter(year == 2018)

df
```


```{r}
df <- df %>% 
  select(state_from, state_to, migration)

df
```

```{r}
df_states <- df %>% 
  select(state_from, state_to, migration) %>% 
  filter(state_from != state_to) %>%
  arrange(state_from, state_to)

df_states
```

```{r}
df_states %>% 
  filter(state_from %in% c("Pennsylvania", "New York", "Ohio", "Virginia", "West Virginia", "Maryland")) %>%
  mutate(state_to = reorder_within(state_to, migration, state_from)) %>%
  arrange(state_from, desc(migration)) %>% 
  group_by(state_from) %>% 
  slice(1:5) %>% 
  ggplot(aes(migration, state_to)) +
    geom_col() +
    facet_wrap(~state_from, scales = "free") +
    scale_y_reordered() +
    scale_x_comma()
```


```{r}
df_states %>% 
  group_by(state_to) %>% 
  summarize(migration = sum(migration, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(desc(migration)) %>% 
  mutate(state_to = fct_reorder(state_to, migration)) %>%
  ggplot(aes(migration, state_to)) +
    geom_col()
```
```{r}
df_ts <- read_csv("output/migration_data_cleaned.csv") %>% 
  select(state_from, year, state_to, migration)

df_ts
```

```{r}
df_cumulative_to <- df_ts %>% 
  filter(state_from %in% c("Pennsylvania", "California", "Texas", "West Virginia"),
         state_from != state_to) %>% 
  arrange(state_from, state_to, year) %>% 
  group_by(state_from, state_to) %>% 
  mutate(migration_cumulative = cumsum(migration)) %>% 
  ungroup()

df_cumulative_to %>% 
  group_by(state_from, state_to) %>% 
  mutate(state_to_label = case_when(year == last(year) ~ state_to,
                                    year != last(year) ~ NA_character_)) %>% 
  ggplot(aes(year, migration_cumulative, group = state_to)) +
    geom_line() +
    geom_label(aes(x = year + 1, label = state_to_label)) +
    facet_wrap(~state_from, scales = "free_y")
```

```{r}
df_cumulative_from <- df_ts %>% 
  filter(state_to %in% c("Pennsylvania", "California", "Texas", "West Virginia"),
         state_to != state_from) %>% 
  arrange(state_to, state_from, year) %>% 
  group_by(state_from, state_to) %>% 
  mutate(migration_cumulative = cumsum(migration)) %>% 
  ungroup()
```

```{r}
df_cumulative_from %>% 
  group_by(state_to, state_from) %>% 
  mutate(state_from_label = case_when(year == last(year) ~ state_from,
                                    year != last(year) ~ NA_character_)) %>% 
  ungroup() %>% 
  ggplot(aes(year, migration_cumulative, group = state_from)) +
    geom_line() +
    geom_label(aes(x = year + .5, label = state_from_label)) +
    facet_wrap(~state_to, scales = "free_y")
```


```{r}
df_migration <- read_csv("output/migration_data_cleaned.csv") %>% 
  select(year, state_from, state_to, migration) %>% 
  filter(state_from != state_to)

df_migration
```

```{r}
df_from <- df_migration %>% 
  group_by(state_from, year) %>% 
  summarize(migration_from = sum(migration, na.rm = TRUE)) %>% 
  rename(state = state_from)

df_to <- df_migration %>% 
  filter(!str_detect(state_to, "Country")) %>% 
  group_by(state_to, year) %>% 
  summarize(migration_to = sum(migration, na.rm = TRUE)) %>% 
  rename(state = state_to)

df_net <- df_from %>% 
  full_join(df_to, by = c("state", "year")) %>% 
  mutate(migration_net = migration_to - migration_from)
```


```{r}
df_net %>% 
  #group_by(state) %>% 
  mutate(state_label = case_when(year == last(year) ~ state,
                                 year != last(year) ~ NA_character_)) %>% 
  ggplot(aes(year, migration_net, group = state)) +
    geom_line() +
    geom_label(aes(x = year + .5, label = state_label))
```

```{r}
df_net %>% 
  #group_by(state) %>% 
  mutate(state_label = case_when(year == last(year) ~ state,
                                 year != last(year) ~ NA_character_)) %>% 
  group_by(state) %>% 
  mutate(migration_net_cumulative = cumsum(migration_net)) %>% 
  ggplot(aes(year, migration_net_cumulative, group = state)) +
    geom_line() +
    geom_label(aes(x = year + .5, label = state_label)) +
    scale_y_comma()
```

```{r}
df_net %>% 
  #group_by(state) %>% 
  mutate(state_label = case_when(year == last(year) & state == "Pennsylvania" ~ state,
                                 TRUE ~ NA_character_),
         state_flag = state == "Pennsylvania") %>% 
  ggplot(aes(year, migration_net, alpha = state_flag, group = state)) +
    geom_line() +
    geom_label(aes(x = year + .5, label = state_label)) +
    scale_y_comma()

df_migration %>% 
  filter(state_from == "Pennsylvania") %>% 
  mutate(domestic_flag = str_detect(state, "Foreign")) %>% 
  group_by(state, year, domestic_flag) %>% 
  summarize(migration_net)
```

```{r}
df_net %>% 
  ggplot(aes(migration_from, migration_to)) +
    geom_abline(linetype = 2, alpha = .3) +
    geom_point(alpha = .5) +
    geom_label_repel(data = df_net %>% filter(state == "California"), aes(label = state)) +
    facet_wrap(~year) +
    coord_equal()
```




